name: Subfolder Correction

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    fix:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Git Config
              run: |
                  git config user.name "GitHub Actions Bot"
                  git config user.email "<>"

            - name: Fix
              run: |
                  git add src
                  git commit -m "Initial dist subtree commit"
                  git subtree push --prefix src origin gh-pages
